### ISSUE TITLE
Suspected error from dev module when using magerun

### ISSUE THREAD

**Issue by freestream** [albertdahlin/magento-dev#4]
The following happens when trying to install a new Magento 1.9.1 using Magerun and having dev module in preprepend.

``` shell
# magento  magerun install

Warning: include(N98/Magerun/Bootstrap.php): failed to open stream: No such file or directory in /var/www/magento191/magento/lib/Varien/Autoload.php on line 94

Warning: include(): Failed opening 'N98/Magerun/Bootstrap.php' for inclusion (include_path='/var/www/modules/magento-dev/magento/Code:/var/www/magento191/magento/app/code/local:/var/www/magento191/magento/app/code/community:/var/www/magento191/magento/app/code/core:/var/www/magento191/magento/lib:.:/usr/share/php:/usr/share/pear') in /var/www/magento191/magento/lib/Varien/Autoload.php on line 94
Cannot initialize Magento. Please check your configuration. Some n98-magerun command will not work. Got message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento_magento191.core_website' doesn't exist, query was: SELECT `core_website`.`website_id`, `core_website`.`code`, `core_website`.`name` FROM `core_website`
```

``` shell
  [Exception]
  Installation failed.
  Notice: Constant DS already defined in /var/www/magento191/magento/app/Mage.php on line 27
  Notice: Constant PS already defined in /var/www/magento191/magento/app/Mage.php on line 28
  Notice: Constant BP already defined in /var/www/magento191/magento/app/Mage.php on line 29
  Fatal error: Uncaught exception 'Mage_Core_Exception' with message 'Mage registry key "original_include_path" already exists' in
   /var/www/magento191/magento/app/Mage.php:595
  Stack trace:
  #0 /var/www/magento191/magento/app/Mage.php(223): Mage::throwException('Mage registry k...')
  #1 /var/www/magento191/magento/app/Mage.php(31): Mage::register('original_includ...', '/var/www/magent...')
  #2 /var/www/magento191/magento/install.php(125): require('/var/www/magent...')
  #3 {main}
    thrown in /var/www/magento191/magento/app/Mage.php on line 595
```

**Comment by albertdahlin** [comment]
This was due to magerun and the devmodule both trying to include Mage.php. I've added magerun to the blacklist so it should work now.
